blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns = [
    path('',views.all_blog,name='all_blog'),
    path('<int:blog_id>',views.detail,name='det'),
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
app_name='portfolio'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	title= models.CharField(max_length=100)
	description= models.TextField()
	date=models.DateField()

	def __str__(self):
		return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
	title=models.CharField(max_length=100)
	description=models.CharField(max_length=250)
	image=models.ImageField(upload_to='portfolio/images/')
	url=models.URLField(blank=True)

	def __str__(self):
		return self.title
	

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
# Create your views here.
def all_blog(request):
	obj=Blog.objects.order_by('-date')
	return render(request,'blog/all_blog.html',{'Blogs':obj})
def detail(request,blog_id):
	blog=get_object_or_404(Blog, pk=blog_id)
	return render(request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.
def home(request):
	projects=Project.objects.all()

	return render(request,'portfolio/home.html',{'project':projects})

blog/templates/blog/all_blog.html
{%extends 'portfolio/base.html' %}
	{% block content %}

		<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

		<h3 class="text-center mb-5">Deepak has written {{ Blogs.count }} blog{{ Blogs.count|pluralize }}</h3>

		{%for blog in Blogs %}

		<div class="row justify-content-center my-3">
  			<div class="col-md-10">
    			<a href="{% url 'blog:det' blog.id %}">
      				<h2>{{ blog.title }}</h2>
    			</a>
    			<h5 class="text-muted">{{ blog.date|date:'M d Y'|upper }}</h5>
    			<h4>{{ blog.description|striptags|truncatechars:100 }}</h4>
  			</div>
		</div>
		{%endfor%}

	{% endblock %}

blog/templates/blog/detail.html
{%extends 'portfolio/base.html' %}
	{% block content %}

	<h1 class="text-center mt-5" id="blogdetailtitle">{{blog.title}}</h1>
	<h5 class="text-center text-muted mb-5">--{{blog.date|date:'F jS Y'}}--</h5>
	<p>{{blog.description|safe}}</p>
	{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Deepak</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active" style="padding-right:900px; padding-left: 10px">
        <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Deepak's Logo" >
        <span style="padding-left: 5px">Deepak</span>
      </a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:all_blog' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% static 'portfolio/Deepak.pdf' %}">Resume</a>
      </li>
      <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/deepakdhull80/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/deepakdhull80" target="_blank">Twitter</a>
          </li>
    </ul>
  </div>
</nav>
    <p align="center">
    {% block content %}{% endblock %}
    </p>

	 <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/robo.gif' %}" class="img-fluid">
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Deepak is Commander-in-Chief at Techphobiax and lives in India 😊</h1>
  </div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for pro in  project %}
  <div class="col-lg-4 col-md-6">

    {% if pro.url %}
    <a href="{{ pro.url }}">
      <img src="{{ pro.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ pro.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ pro.title }}</h3>
    <p>{{ pro.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock %}